export * from './MailIcon'
export * from './PhoneIcon'
export * from './ReactIcon'
export * from './ReduxIcon'
export * from './TsIcon'
export * from './SwiftIcon'
export * from './SwiftUIIcon'
export * from './Xcode'